# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; use os_env for environment variables
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(minute).2d-%%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# prepend the current working directory to the sys.path
prepend_sys_path = .

# version location specification; This defaults to alembic/versions.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# the output encoding used when writing the revision file
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://infraos:infraos_password@localhost:5432/infraos_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%(H):%%(M):%%(S)
